### ISSUE TITLE
Support Web Animations API

### ISSUE THREAD

**Issue by laggingreflex** [tungs/timesnap#21]
Would it be possible, and if so please add support for [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Using_the_Web_Animations_API)

**Comment by tungs** [comment]
It's an interesting and potential idea, since Web Animations look like they operate a lot like videos and they have a `currentTime` property. Alternatively, [the polyfill](https://github.com/web-animations/web-animations-js) itself might work if modified to always overwrite the native `Element.animate`.

**Comment by tungs** [comment]
All of the in-browser time handling code got moved to `timeweb`. I've opened up the corresponding issue at tungs/timeweb#4

**Comment by ferbs** [comment]
@tungs I wonder if another potential approach might work: using a DevTools session to watch for Animation.animationStarted events, pausing each, and then setting their time using [seek](https://chromedevtools.github.io/devtools-protocol/tot/Animation/#method-seekAnimations) before each screenshot?
