### ISSUE TITLE
[BUG] startDelay not working for animations

### ISSUE THREAD

**Issue by lindsgil** [tungs/timesnap#72]
**Describe the bug**
I have a website that generates art from different creative coding JavaScript libraries (p5.js, three.js, etc). When capturing video of the animations it's not always desirable to start from page load. Setting `startDelay` in the timecut configuration doesn't seem to load the page and run animations for the designated time, so no matter the `startDelay` value it appears that the animation starts from the beginning each time. 

**To Reproduce**

Timecut configuration: 
```
    const navigatePageToURL = async ({ page, url }: { page: any; url: any }) => {
      await page.goto(url, {
        timeout: 0
      })
    }
    const timeCutConfig = {
      url: 'https://generator.artblocks.io/0xa7d8d9ef8d8ce8992df33d8b8cf4aebabd5bd270/364000001',
      fps: 24,
      duration: 5,
      startDelay: 60,
      viewport: {
        width: 2400,
        height: 2400
      },
      launchArguments: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--use-gl=egl'],
      navigatePageToURL: navigatePageToURL,
      output: `out.mp4`,
      ffmpegPath: ffmpegPath
    }
```

**Expected behavior**
I would expect that the animation would play after page load for the designated `startDelay` time set before video capture begins.

**Attachments and Screenshots**
If applicable to a local, publicly unavailable web site, upload a minimal reproducible example. Also if applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS Monterey v12.6
 - Node Version: v16.17.0
 - Timesnap Version: 0.3.3

**Additional context**
I replaced lines 204 - 210 of index.js with this, which seemed to fix the problem
```
   var animatedFramesToCapture = config.startDelay ? config.startDelay * fps : 1;
    var totalFramesToCapture = animatedFramesToCapture + framesToCapture;

    for (let i = 1; i <= animatedFramesToCapture; i ++) {
      addMarker({
        time: frameNumToTime(i, totalFramesToCapture),
        type: 'Only Animate'
      });
    }
    for (let i = animatedFramesToCapture; i <= totalFramesToCapture; i++) {
      addMarker({
        time: delayMs + frameNumToTime(i, totalFramesToCapture),
        type: 'Capture',
        data: { frameCount: i - animatedFramesToCapture + 1 }
      });
      captureTimes.push(delayMs + frameNumToTime(i, totalFramesToCapture));
    }
```

**Comment by tungs** [comment]
Hi @lindsgil, thanks for your interest! Just to confirm that I understand, it sounds like you want your capture your animations mid-animation at an arbitrary start time. If that's the case, you should use [`config.start`](https://github.com/tungs/timesnap#js-config-start) instead of `config.startTime`.

`config.startTime` waits in **real-time** time without incrementing virtual time. It's useful if the page requires assets loading or other real-time events. [`config.start`](https://github.com/tungs/timesnap#js-config-start) deals with **virtual** time, which sounds like what you want.

Let me know if you run into any problems. Thanks for your interest in this project!

**Comment by lindsgil** [comment]
Hey @tungs thanks for your quick response! That's correct, would like to wait a certain number of virtual-time seconds before capturing the animation.. I've tried setting the `start` value but that doesn't seem to be working for me either. Are virtual-seconds and real-time seconds nearly 1:1? I tried setting `start: 600` and visiting this website https://generator.artblocks.io/0xa7d8d9ef8d8ce8992df33d8b8cf4aebabd5bd270/364000000 but not noticing any meaningful different between a start of 600 and a start of 0. 

Thanks for your help!

**Comment by tungs** [comment]
Ah, it looks like your animation uses `requestAnimationFrame` to update your application state instead of (or in addition to) using a time delta. As it looks like you've discovered, by default, timesnap only runs the functions specified in `requestAnimationFrame` once per frame capture, and when you use `config.start` it jumps to that time.

### Using `config.shouldSkipFrame`
Instead of using `config.start` or `config.startDelay`, you could use [`config.shouldSkipFrame`](https://github.com/tungs/timesnap#js-config-should-skip-frame). If the function returns true, timesnap skips capturing the frame, though it will run frame animations in either case.

So instead of doing something like this:
```
var timeCutConfig = {
      // ...
      fps: 24,
      duration: 5,
      start: 60,
```

You could do something like this:
```
var timeCutConfig = {
      // ...
      fps: 24,
      duration: 65, // the time to skip (60) + duration (5)
      shouldSkipFrame: function (c) {
        return c.frameCount <= (60 * 24);  // skip the first 60 seconds worth of frames
      }
```

The disadvantage of using this route is that the file naming still counts the skipped frames (so it would start at something like `frame-001441.png`), but if you're using timecut the file names would probably be ignored anyway when converting to a video.

**Comment by tungs** [comment]
For the other part:
> Are virtual-seconds and real-time seconds nearly 1:1?

The library tries to make the resulting animation captured from virtual-time look as though it's from real-time, so in that sense it aims to be 1:1. This becomes trickier when the state of the program depends on the frequency that animation frames from `requestAnimationFrame` is called and the user jumps multiple frames ahead. By default, when jumping to a virtual time (like by using `config.start`), it's as though the tab is slept for that interval, so no animation frames are run during that jump.

Running only one set of animation frames per time seek by default is a deliberate design decision, since running multiple animation frames unnecessarily can have performance implications. It's possible to override this behavior using the undocumented (and untested) `config.maximumAnimationFrameDuration`, that inserts animation frames if the interval between the seeks exceeds a certain amount of time in milliseconds. It's a little tricky (and not recommended) to use this, since you don't want it to insert animation frames during normal capture, which means the duration would have to be slightly higher than the capture frame rate duration. This (slight) mismatch between animation frame durations during the skipped part and the captured part might have some implications, depending on use case.

**Comment by lindsgil** [comment]
Thank you so much for both the explanation and the `shouldSkipFrame` example. I just gave that a shot and it works great! Really appreciate the help :)
